sudo: false
dist: trusty
language: ruby
rvm:
- 2.2
branches:
  only:
  - master
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- rm -rf dependencies/jekyll/.git/
- rm -rf dependencies/jekyll/*.md
- mv dependencies/jekyll/* .
- rm -rf dependencies
- mv sidebar.yml _data/sidebars/
- sed -i 's/\/jekyll/'$JEKYLL_BASEURL'/g' ./_config.yml
script:
- bundle exec rake deploy
