---
sidebar: sidebar
permalink: concept_backup_policies.html
keywords: netapp, saas backup, microsoft 365, backup, policies, byos, provides, storage, tiers, tier 1, tier 2, tier 3, frequency, default, data, retention,
summary: SaaS Backup for microsoft 365 has three predefined tiers of backup policies.  These policy tiers vary in backup frequency and data retention period, depending upon whether you are using SaaS Backup provided storage or BYOS.
---

= Backup policies
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
SaaS Backup for Microsoft 365 has three predefined tiers of backup policies.  These policy tiers vary in backup frequency and data retention period, depending upon whether you are using SaaS Backup provided storage or BYOS.

You can move data between the three policies, but you cannot create new policies or change the parameters of the predefined tiers.

== Backup policies for SaaS Backup provided storage

[options="header" width="80%"]
|=======
|Backup policy |Backup frequency |Default data retention period
|Tier 1 |Once every 12 hours |3 years
|Tier 2 |Once every 18 hours |3 years
|Tier 3 |Once every 24 hours |3 years
|=======

NOTE: As an administrator, you can change the data retention period for SaaS Backup provided storage up to an unlimited period of time. SaaS Backup retains the backup data for the retention period if the subscription is active.

== Backup policies for BYOS

[options="header" width="80%"]
|=======
|Backup policy |Backup frequency |Default data retention period
|Tier 1 |Once every 12 hours |Unlimited
|Tier 2 |Once every 18 hours |Unlimited
|Tier 3 |Once every 24 hours |Unlimited
|=======
