---
sidebar: sidebar
permalink: concept_backup_settings.html
keywords: netapp, saas backup, office 365, backup, setting, updating, autosync, enable, restore, recoverable, items, backup, list, views, version, history, workflows
summary: You can update your backup settings to control various backup options. Available backup settings vary based on service.
---

= Backup settings
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can update your backup settings to control various backup options. Available backup settings vary based on service.

[cols=4*,options="header",cols="12,64,24,24"]
|===
|Backup setting
|Description
|Enabled
|Available in...

// |Enabled Advanced Search a|
//Enables the user to

// |Disabled a|

//* Microsoft Exchange Online

|Auto Sync a|
Enables the automatic scheduled synchronization of newly added or deleted users, OneDrives, or site collections once every 24 hours.
|By default a|

* Microsoft Exchange Online
* Microsoft SharePoint Online
* Microsoft OneDrive for Business
* Microsoft Office 365 Groups

|Enable OneNote Backup a|
Enables the backup of OneNote notebooks.
|Manually a|

* Microsoft SharePoint Online
* Microsoft OneDrive for Business
|Enable Restore of Recoverable Items a|
Enables the user to restore Microsoft Exchange recoverable items.
|Manually a|

* Microsoft Exchange Online

|Enable Backup of Recoverable Items a|
Enables the backup of Microsoft Exchange recoverable items.  Only the tier 1 backup policy allows for the backup of recoverable items.
|Manually a|

* Microsoft Exchange Online

|Include Workflows a|
Includes workflows in the backup.
|Manually a|

* Microsoft SharePoint Online
* Microsoft Office 365 Groups

|Include List Views a|
Includes list views in backup.
|Manually a|

* Microsoft SharePoint Online
* Microsoft Office 365 Groups

|Include Version History a|
Enables maintenance of multiple file versions in the backup.

NOTE: This setting only applies to individual files.  It does not apply to entire folders, tiers, or services.

|By default a|

* Microsoft SharePoint Online
* Microsoft OneDrive for Business
* Microsoft Office 365 Groups

|Number of Versions a|
Sets the number of backup file versions to maintain.
By default, the latest version is automatically backed up, even if this setting is not enabled.
|Set to 20 by default a|

* Microsoft SharePoint Online
* Microsoft OneDrive for Business
* Microsoft Office 365 Groups
|===
