---
sidebar: sidebar
permalink: reference_kpls.html
keywords: what's new, features, new, release notes, known, problems, limitations
summary: SaaS Backup for Office 365 regularly introduces a new release to bring you new features, enhancements, and bug fixes.
---

= Known problems and limitations
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

* The following limitations exist for TeamsChat:

** Team Level Restore Limitations
***	Restore of content to same team is not supported.
*** Restore of Tabs is possible but restore of tab content is not.
*** Restore to different team is not supported.
*** Restore of Mailbox & SharePoint data only, not conversations.
*** Restore of deprovisioned (deleted) items to the same team option always fails. Only Export to Data is supported. 

** Channel Level Restore Limitations
*** Tab content restore is not supported.
*** Export to Data restore is not supported.

** Conversation Level Restore Limitations
*** Only export option is Export to HTML.
**** Exported HTML generates conversation ID instead of conversation name.
**** Unable to view attachment links posted in conversations in the html document.

** Product features that are not supported because of API limitations
*** Restore of one or more conversations to the same channel or another channel.
*** Restore of one channel to another channel from SaaS Backup Portal.
*** Microsoft notifications for deleted or updated events, such as notification for a deleted mailbox.
*** Backup or restore of emojis & gifs.
*** Identification of private or public channels like in Microsoft
*** Export to Data failure for teams with team names containing special characters.
*** Inability to remove sync state information and conversation data, such as json or .pst files, during a purge.


* The following limitations exist for OneNote:
** Export to data is not available.
** Incremental backup job might fail with the following error message:  `Partial Failure.  Failed to back up few OneNote Sections`
** OneDrive backup includes the backup of .onebak files.
** Restore statistics are not available for download.
* Partially failed job status for restore of site collection group
  If an entire site collection group is deleted, the restore of private groups in the collection fails, resulting in a restore job status of “partially failed.”  If this happens, the site is not accessible from the GUI.
* The following are not supported for OneNote:
** Data export
** Data purge
* “Partial Failure. Failed to back up few Onenote Sections”
