---
sidebar: sidebar
permalink: reference_kpls.html
keywords: what's new, features, new, release notes, known, problems, limitations
summary: SaaS Backup for Office 365 regularly introduces a new release to bring you new features, enhancements, and bug fixes.
---

= Known problems and limitations
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


* The following limitations exists for OneNote:
** Export to data is not available.
** Incremental backup job might fail with the following error message:  `Partial Failure.  Failed to back up few OneNote Sections`
** OneDrive backup includes the backup of .onebak files.
** Restore statistics are not available for download.
* Partially failed job status for restore of site collection group
  If an entire site collection group is deleted, the restore of private groups in the collection fails, resulting in a restore job status of “partially failed.”  If this happens, the site is not accessible from the GUI.
* The following are not supported for OneNote:
** Data export
** Data purge
* “Partial Failure. Failed to back up few Onenote Sections”
