---
sidebar: sidebar
permalink: reference_kpls.html
keywords: what's new, features, new, release notes, known, problems, limitations, application
summary: SaaS Backup for Microsoft 365 regularly introduces a new release to bring you new features, enhancements, and bug fixes.
---

= Known problems and limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following are known limitations identified at the application level for SaaS Backup for Microsoft 365.

== For Microsoft 365 OneDrive for Business
Newly added drives are not detected until you manually complete a sync for the service.

== For Microsoft 365 Exchange Online
*	SaaS Backup does not support backups for public folders.
*	*Advanced Search* is only available for Exchange Online. The setting is disabled by default. A customer must request to enable this feature. After the Enable Advanced Search setting is enabled, administrators must manually enable the search feature for individual users.

== For Microsoft 365 Teams
*	Channel configuration is restored but content and conversations are not.
*	Due to API limitations, SaaS Backup cannot differentiate between public and private channels in SaaS Backup.
*	High-level restore restores Mailbox & SharePoint data only, not conversations.
*	Backup or restore for emojis and gifs is not supported in Teams Chat.
*	Team chat conversations only export option is Export to HTML.
Attachment links posted in conversations are not visible in the html document.

== For Microsoft 365 OneNote
*	Export to data is not available.
*	Incremental backup job might fail with the following error message:
`Partial Failure. Failed to back up few OneNote Sections`.
*	OneDrive backups include the backup of .onebak files.
*	Restore statistics are not available for download.
*	Data export and data purge are not supported.

== Other problems and limitations

For Self Service Portal:
* Only Exchange Online is supported.
* SaaS Backup holds the backup data for a maximum of 30 days.
* Primary user mailboxes are supported, not shared or archive mailboxes.

The following known problems and limitations are not specific to one application.

For all users who sign up with a Microsoft 365 service account:

* SaaS Backup supports Basic Authentication only.

For free trial users:

*	A maximum of 10 restores per service are allowed in a 24-hour period.

For licensed users:

*	A maximum of 10 export data restores per service are allowed in a 24-hour period. All other restore options have no limitations.

For restores of site collection groups:

*	If an entire site collection group is deleted, the restore of private groups in the collection fails, resulting in a restore job status of “partially failed.” If this happens, the site is not accessible from the GUI.

For *Advanced Search*:

* A maximum of 10 search jobs are allowed in a 24-hour period.
