---
sidebar: sidebar
permalink: task_completing_signing_up_ipa.html
keywords: netapp, saas backup, office 365, getting started, signing up, paid, subscription, licensed, version
summary: You can sign up for SaaS Backup for Office 365 with your Microsoft Office 365 service account or with your NetApp SSO account.
---

= Signing up with paid subscription
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you purchased your license through NetApp, your subscription types are displayed. Complete the sign up process by following these steps.

.Steps

. Select *Licensed* for the subscription type.
. Enter the requested information, and then validate the subscription.
. Click *Next*.
.	Select your backup storage option.
  You can use storage provided by SaaS Backup or the Bring Your Own Storage (BYOS) option.
.. If you are using storage provided by SaaS Backup do the following:
... Click *SaaS Backup Provided Storage*.
... Select the *Amazon S3* or *Azure Blob* storage option.
... Select the *AWS S3* or *Azure Blob* region for your backup.
    You should select the region that is the closest to the physical location of the data you are backing up.
... Click *Next*.
... Review your configuration, and then click *Save*.

.. If you are using a BYOS option do the following:
... Click *Bring Your Own Storage (BYOS)*.
... Click your BYOS option.
... Enter the information you previously gathered for your BYOS option.
... Click *Test Connection*.
... Click *Next*.
... Review your configuration, and then click *Save*.
