---
sidebar: sidebar
permalink: task_viewing_history_and_activity.html
keywords: netapp, saas backup, microsoft 365, view, viewing, jobs, history, activity, log
summary: You can view or download a log of the SaaS Backup activities and job history.
---

= View job history and activity log
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
SaaS Backup for Microsoft 365 stores a log of your job history and a log of all activities performed inside SaaS Backup.

== View job history
You can view or download reports of all your job history in NetApp SaaS Backup for Office 365. You can filter your search by job type, service, start time, end time, and completion status.

.Steps

.	Click *Reporting* on the left navigation pane.
A list of all SaaS Backup jobs is displayed under the *Job History* tab.
.	To filter the results, click *Filter*.
.	Click the *Select* drop-down menu, and select a filter.
  You can filter by policy, service, type, or status. After you select a filter, a search field appears.
.	Enter your search criteria.
.	If you want to add more filters, click *Add Filter*.
.	Click *Apply Filter*.
Filter results are displayed.
.	Click any job to expand the view for additional job details.

== View the activity log
A log is stored of all activity that occurs inside SaaS Backup for Microsoft 365.  The log contains the date of each action performed along with the name of the user who performed the action. You can filter the activity log by service and event. For example, if you need to see all of the restore operations that have occurred for Microsoft Exchange Online, you can filter the activity log to view those specific results.

.Steps

.	Click *Reporting* on the left navigation pane.
.	Click the *Activity Log* tab.
  A list of all SaaS Backup for Microsoft 365 activity is displayed.
.	To filter the results, click *Filter*.
.	Click the *Select* drop-down menu, and select a filter.
  You can filter by service or event.  After you select a filter, a search field appears.
.	Enter your search criteria.
.	If you want to add more filters, click *Add Filter*.
.	Click *Apply Filter*.
+
Filter results are displayed.
