---
sidebar: sidebar
permalink: task_completing_signing_up_ipa.html
keywords: netapp, saas backup, microsoft 365, getting started, sign up, signing up, paid, subscription, licensed, version
summary: You can sign up for SaaS Backup for Microsoft 365 with your Microsoft 365 service account or with your NetApp SSO account.
---

= Sign up with paid subscription
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you purchased your license through NetApp, your subscription types are displayed. Complete the sign up process by following these steps.

.Before you begin
To validate your subscription, you must have a NetApp SSO user ID and password.  If you do not have a NetApp SSO account, go to https://mysupport.netapp.com/eservice/public/now.do to register for one. After your request has been processed, you will receive an email notification containing your NetApp SSO credentials.  It will take approximately 24 hours to process the request and send the notification email.

.Steps

. Select *Licensed* for the subscription type.
. Enter the requested information, and then validate the subscription.
. Click *Next*.
.	Select your backup storage option.
.. Click *SaaS Backup Provided Storage*.
.. Select the *Amazon S3* or *Azure Blob* storage option.
.. Select the *AWS S3* or *Azure Blob* region for your backup.
    You should select the region that is the closest to the physical location of the data you are backing up.
.. Click *Next*.
.. Review your configuration, and then click *Save*.
