---
sidebar: sidebar
permalink: task_managing_security_groups.html
keywords: netapp, saas backup, office 365, security, groups
summary: You can manage your service in various ways within NetApp SaaS Backup including activating a new services, deactivating a existing services, purging data, and canceling a job.
---

= Managing security groups
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Security groups can be used as filtering options to view your data and to create rules.

toc::[]

== Adding security groups
You can add up to 3 security groups.  You can then use your security groups as filtering options in SaaS Backup.

New security groups must be discovered through an AutoSync or a manual synchronization before they can be added.
https://docs.microsoft.com/en-us/office365/admin/email/create-edit-or-delete-a-security-group?view=o365-worldwide[Create, edit, or delete a security group in the Admin Center].

.Steps

. Click *ACCOUNT SETTINGS*.
. Click *SECURITY GROUPS*.
. In the search field, enter the name of the security group you want to add.
. Click *Add*.

== Deleting security groups
If a security group is being utilized in a user-defined rule, it cannot be deleted.  You must remove the user-defined rule, then delete the security group.
<<task_managing_creating_rules.adoc#deleting-rules, Deleting rules>>

.Steps
. Click *ACCOUNT SETTINGS*.
. Click *SECURITY GROUPS*.
. Click the delete icon next to the group you want to remove.
